# Generated by Django 5.2.6 on 2025-12-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, help_text='Ej: unidades, kg, metros…', max_length=30)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlataformaOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Plataforma de origen',
                'verbose_name_plural': 'Plataformas de origen',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('REALIZADA', 'Realizada'), ('ENTREGADA', 'Entregada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('imagen_referencia_1', models.ImageField(blank=True, null=True, upload_to='referencias/')),
                ('imagen_referencia_2', models.ImageField(blank=True, null=True, upload_to='referencias/')),
                ('imagen_referencia_3', models.ImageField(blank=True, null=True, upload_to='referencias/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('plataforma_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='mainApp.plataformaorigen')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='mainApp.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
