# Generated by Django 5.2.6 on 2025-12-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_red_social',
            field=models.CharField(blank=True, help_text='Usuario o enlace de red social', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='mainApp.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
