# Generated by Django 5.2.6 on 2025-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_pedido_cliente_email_pedido_cliente_red_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
