# Generated by Django 5.2.6 on 2025-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_pedido_fecha_solicitada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plataformaorigen',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='plataformaorigen',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
